# Generated by Django 4.2.6 on 2023-10-12 05:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipeapp", "0002_alter_recipe_author"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="time",
            field=models.DurationField(),
        ),
    ]
