# Generated by Django 4.2.6 on 2023-10-12 06:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipeapp", "0003_alter_recipe_time"),
    ]

    operations = [
        migrations.CreateModel(
            name="Step",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number_step", models.PositiveIntegerField(max_length=10)),
                ("description", models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name="recipe",
            name="steps",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="recipeapp.step"),
        ),
    ]
