# Generated by Django 4.2.6 on 2023-10-12 06:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipeapp", "0004_step_alter_recipe_steps"),
    ]

    operations = [
        migrations.AlterField(
            model_name="step",
            name="number_step",
            field=models.PositiveIntegerField(),
        ),
    ]
