# Generated by Django 4.2.6 on 2023-10-12 08:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipeapp", "0006_alter_recipe_steps_delete_step"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="category",
            field=models.ManyToManyField(related_name="recipes", to="recipeapp.category"),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="image",
            field=models.ImageField(blank=True, upload_to="images/%Y/%m/%d"),
        ),
        migrations.DeleteModel(
            name="RecipeCategory",
        ),
    ]
