# Generated by Django 4.2.6 on 2023-10-12 08:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipeapp", "0007_recipe_category_alter_recipe_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="image",
            field=models.ImageField(blank=True, upload_to="images/"),
        ),
    ]
